import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StateProvider from "./state_management/provider";
import { useSelector, useDispatch } from "react-redux";
import { setNavBg } from "./state_management/reducers/client-reducers/navBgState";
import { RootState } from "./state_management/stores/store";
import PageContainer from "./PageContainer";
import { interFont } from "./fonts/fontsConfig";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  
  return (
    <html lang="en">
      <body
        id="parentDivRef"
        className={`${interFont.className} antialiased overflow-hidden text-gray-900 bg-gray-400`}
      >
        <StateProvider>
          <PageContainer>
            {children}
          </PageContainer>
          
        </StateProvider>
      </body>
    </html>
  );
}
